USE [master]
GO
/****** Object:  Database [RANDOMPAY]    Script Date: 17/03/2026 14:11:32 ******/
CREATE DATABASE [RANDOMPAY]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RANDOMPAY', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.DEVELOPER\MSSQL\DATA\RANDOMPAY.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'RANDOMPAY_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.DEVELOPER\MSSQL\DATA\RANDOMPAY_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [RANDOMPAY] SET COMPATIBILITY_LEVEL = 170
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RANDOMPAY].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [RANDOMPAY] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [RANDOMPAY] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [RANDOMPAY] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [RANDOMPAY] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [RANDOMPAY] SET ARITHABORT OFF 
GO
ALTER DATABASE [RANDOMPAY] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [RANDOMPAY] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [RANDOMPAY] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [RANDOMPAY] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [RANDOMPAY] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [RANDOMPAY] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [RANDOMPAY] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [RANDOMPAY] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [RANDOMPAY] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [RANDOMPAY] SET  DISABLE_BROKER 
GO
ALTER DATABASE [RANDOMPAY] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [RANDOMPAY] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [RANDOMPAY] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [RANDOMPAY] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [RANDOMPAY] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [RANDOMPAY] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [RANDOMPAY] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [RANDOMPAY] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [RANDOMPAY] SET  MULTI_USER 
GO
ALTER DATABASE [RANDOMPAY] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [RANDOMPAY] SET DB_CHAINING OFF 
GO
ALTER DATABASE [RANDOMPAY] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [RANDOMPAY] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [RANDOMPAY] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [RANDOMPAY] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [RANDOMPAY] SET OPTIMIZED_LOCKING = OFF 
GO
ALTER DATABASE [RANDOMPAY] SET QUERY_STORE = ON
GO
ALTER DATABASE [RANDOMPAY] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [RANDOMPAY]
GO
/****** Object:  Table [dbo].[ACTIVIDADES]    Script Date: 17/03/2026 14:11:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACTIVIDADES](
	[ID_ACTIVIDAD] [int] NOT NULL,
	[NOMBRE_ACTIVIDAD] [nvarchar](200) NOT NULL,
	[ID_CREADOR] [int] NOT NULL,
	[MONEDA_PRINCIPAL] [nvarchar](10) NOT NULL,
	[INVITACION_COD] [nvarchar](50) NOT NULL,
	[FECHA_CREACION] [datetime] NOT NULL,
	[IMAGEN] [nvarchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_ACTIVIDAD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DIVISAS]    Script Date: 17/03/2026 14:11:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DIVISAS](
	[IDDIVISA] [int] NOT NULL,
	[CODIGO] [nvarchar](10) NOT NULL,
	[TASA] [float] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[IDDIVISA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[GASTOS]    Script Date: 17/03/2026 14:11:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GASTOS](
	[ID_GASTO] [int] NOT NULL,
	[ID_ACTIVIDAD] [int] NOT NULL,
	[ID_PAGADOR] [int] NOT NULL,
	[CONCEPTO] [nvarchar](200) NOT NULL,
	[IMPORTE] [decimal](18, 2) NOT NULL,
	[FECHA] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_GASTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LISTA_COMPRA]    Script Date: 17/03/2026 14:11:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LISTA_COMPRA](
	[ID_ITEM] [int] NOT NULL,
	[ID_ACTIVIDAD] [int] NOT NULL,
	[NOMBRE_ITEM] [nvarchar](200) NOT NULL,
	[PRECIO_ESTIMADO] [decimal](18, 2) NOT NULL,
	[COMPRADO] [bit] NOT NULL,
	[ID_GASTO] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_ITEM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PARTICIPANTES]    Script Date: 17/03/2026 14:11:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PARTICIPANTES](
	[ID_PARTICIPANTE] [int] NOT NULL,
	[ID_ACTIVIDAD] [int] NOT NULL,
	[NOMBRE_PARTICIPANTE] [nvarchar](100) NOT NULL,
	[ID_USUARIO] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_PARTICIPANTE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[REPARTOS_GASTO]    Script Date: 17/03/2026 14:11:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REPARTOS_GASTO](
	[IDREPARTO] [int] NOT NULL,
	[IDGASTO] [int] NOT NULL,
	[IDPARTICIPANTE] [int] NOT NULL,
	[CANTIDAD] [float] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[IDREPARTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SEGURIDAD_USUARIOS]    Script Date: 17/03/2026 14:11:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SEGURIDAD_USUARIOS](
	[ID_USUARIO] [int] NOT NULL,
	[SALT] [nvarchar](50) NOT NULL,
	[PASSWORD_HASH] [varbinary](max) NOT NULL,
	[TOKEN_RECUPERACION] [nvarchar](100) NULL,
	[TOKEN_EXPIRACION] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_USUARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USUARIOS]    Script Date: 17/03/2026 14:11:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USUARIOS](
	[ID_USUARIO] [int] NOT NULL,
	[NOMBRE] [nvarchar](100) NOT NULL,
	[EMAIL] [nvarchar](100) NOT NULL,
	[PASSWORD] [nvarchar](255) NOT NULL,
	[ROL] [nvarchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_USUARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[ACTIVIDADES] ([ID_ACTIVIDAD], [NOMBRE_ACTIVIDAD], [ID_CREADOR], [MONEDA_PRINCIPAL], [INVITACION_COD], [FECHA_CREACION], [IMAGEN]) VALUES (3, N'Cervezas Viernes', 1, N'EUR', N'C45BE05A', CAST(N'2026-03-16T09:30:00.680' AS DateTime), NULL)
INSERT [dbo].[ACTIVIDADES] ([ID_ACTIVIDAD], [NOMBRE_ACTIVIDAD], [ID_CREADOR], [MONEDA_PRINCIPAL], [INVITACION_COD], [FECHA_CREACION], [IMAGEN]) VALUES (5, N'qqqqq', 1, N'EUR', N'3E3C71C3', CAST(N'2026-03-16T10:21:50.197' AS DateTime), N'/images/actividades/a98669ae-c367-4124-a589-4e95d4c43b08.png')
INSERT [dbo].[ACTIVIDADES] ([ID_ACTIVIDAD], [NOMBRE_ACTIVIDAD], [ID_CREADOR], [MONEDA_PRINCIPAL], [INVITACION_COD], [FECHA_CREACION], [IMAGEN]) VALUES (6, N'Viaje Japon', 4, N'EUR', N'77F202F1', CAST(N'2026-03-17T13:46:34.587' AS DateTime), N'✈️')
GO
INSERT [dbo].[DIVISAS] ([IDDIVISA], [CODIGO], [TASA]) VALUES (1, N'EUR', 1)
INSERT [dbo].[DIVISAS] ([IDDIVISA], [CODIGO], [TASA]) VALUES (2, N'USD', 1.09)
INSERT [dbo].[DIVISAS] ([IDDIVISA], [CODIGO], [TASA]) VALUES (3, N'GBP', 0.85)
INSERT [dbo].[DIVISAS] ([IDDIVISA], [CODIGO], [TASA]) VALUES (4, N'JPY', 162.5)
GO
INSERT [dbo].[GASTOS] ([ID_GASTO], [ID_ACTIVIDAD], [ID_PAGADOR], [CONCEPTO], [IMPORTE], [FECHA]) VALUES (9, 5, 16, N'💸 Reembolso de deuda', CAST(1148.00 AS Decimal(18, 2)), CAST(N'2026-03-16T10:43:10.307' AS DateTime))
INSERT [dbo].[GASTOS] ([ID_GASTO], [ID_ACTIVIDAD], [ID_PAGADOR], [CONCEPTO], [IMPORTE], [FECHA]) VALUES (10, 5, 15, N'barbacoa', CAST(45.00 AS Decimal(18, 2)), CAST(N'2026-03-16T14:11:19.017' AS DateTime))
INSERT [dbo].[GASTOS] ([ID_GASTO], [ID_ACTIVIDAD], [ID_PAGADOR], [CONCEPTO], [IMPORTE], [FECHA]) VALUES (11, 6, 20, N'cena', CAST(120.00 AS Decimal(18, 2)), CAST(N'2026-03-17T13:47:10.020' AS DateTime))
INSERT [dbo].[GASTOS] ([ID_GASTO], [ID_ACTIVIDAD], [ID_PAGADOR], [CONCEPTO], [IMPORTE], [FECHA]) VALUES (12, 6, 20, N'Cervezas', CAST(15.00 AS Decimal(18, 2)), CAST(N'2026-03-17T13:48:09.230' AS DateTime))
INSERT [dbo].[GASTOS] ([ID_GASTO], [ID_ACTIVIDAD], [ID_PAGADOR], [CONCEPTO], [IMPORTE], [FECHA]) VALUES (13, 6, 20, N'VVVVV', CAST(44.00 AS Decimal(18, 2)), CAST(N'2026-03-17T14:07:07.600' AS DateTime))
INSERT [dbo].[GASTOS] ([ID_GASTO], [ID_ACTIVIDAD], [ID_PAGADOR], [CONCEPTO], [IMPORTE], [FECHA]) VALUES (14, 6, 20, N'GGGG', CAST(34.00 AS Decimal(18, 2)), CAST(N'2026-03-17T14:08:27.573' AS DateTime))
GO
INSERT [dbo].[LISTA_COMPRA] ([ID_ITEM], [ID_ACTIVIDAD], [NOMBRE_ITEM], [PRECIO_ESTIMADO], [COMPRADO], [ID_GASTO]) VALUES (1, 3, N'Entradas', CAST(233.00 AS Decimal(18, 2)), 0, NULL)
INSERT [dbo].[LISTA_COMPRA] ([ID_ITEM], [ID_ACTIVIDAD], [NOMBRE_ITEM], [PRECIO_ESTIMADO], [COMPRADO], [ID_GASTO]) VALUES (2, 5, N'barbacoa', CAST(45.00 AS Decimal(18, 2)), 1, 10)
INSERT [dbo].[LISTA_COMPRA] ([ID_ITEM], [ID_ACTIVIDAD], [NOMBRE_ITEM], [PRECIO_ESTIMADO], [COMPRADO], [ID_GASTO]) VALUES (3, 6, N'Cervezas', CAST(15.00 AS Decimal(18, 2)), 1, 12)
INSERT [dbo].[LISTA_COMPRA] ([ID_ITEM], [ID_ACTIVIDAD], [NOMBRE_ITEM], [PRECIO_ESTIMADO], [COMPRADO], [ID_GASTO]) VALUES (4, 6, N'VVVVV', CAST(44.00 AS Decimal(18, 2)), 1, 13)
INSERT [dbo].[LISTA_COMPRA] ([ID_ITEM], [ID_ACTIVIDAD], [NOMBRE_ITEM], [PRECIO_ESTIMADO], [COMPRADO], [ID_GASTO]) VALUES (5, 6, N'GGGG', CAST(34.00 AS Decimal(18, 2)), 1, 14)
GO
INSERT [dbo].[PARTICIPANTES] ([ID_PARTICIPANTE], [ID_ACTIVIDAD], [NOMBRE_PARTICIPANTE], [ID_USUARIO]) VALUES (8, 3, N'Carlos', 1)
INSERT [dbo].[PARTICIPANTES] ([ID_PARTICIPANTE], [ID_ACTIVIDAD], [NOMBRE_PARTICIPANTE], [ID_USUARIO]) VALUES (9, 3, N'Kevin', NULL)
INSERT [dbo].[PARTICIPANTES] ([ID_PARTICIPANTE], [ID_ACTIVIDAD], [NOMBRE_PARTICIPANTE], [ID_USUARIO]) VALUES (10, 3, N'Julio', NULL)
INSERT [dbo].[PARTICIPANTES] ([ID_PARTICIPANTE], [ID_ACTIVIDAD], [NOMBRE_PARTICIPANTE], [ID_USUARIO]) VALUES (11, 3, N'Jose', NULL)
INSERT [dbo].[PARTICIPANTES] ([ID_PARTICIPANTE], [ID_ACTIVIDAD], [NOMBRE_PARTICIPANTE], [ID_USUARIO]) VALUES (12, 3, N'Angel', NULL)
INSERT [dbo].[PARTICIPANTES] ([ID_PARTICIPANTE], [ID_ACTIVIDAD], [NOMBRE_PARTICIPANTE], [ID_USUARIO]) VALUES (13, 3, N'Pepito', NULL)
INSERT [dbo].[PARTICIPANTES] ([ID_PARTICIPANTE], [ID_ACTIVIDAD], [NOMBRE_PARTICIPANTE], [ID_USUARIO]) VALUES (15, 5, N'Carlos', 1)
INSERT [dbo].[PARTICIPANTES] ([ID_PARTICIPANTE], [ID_ACTIVIDAD], [NOMBRE_PARTICIPANTE], [ID_USUARIO]) VALUES (16, 5, N'dddd', 1)
INSERT [dbo].[PARTICIPANTES] ([ID_PARTICIPANTE], [ID_ACTIVIDAD], [NOMBRE_PARTICIPANTE], [ID_USUARIO]) VALUES (17, 5, N'ddddddd', NULL)
INSERT [dbo].[PARTICIPANTES] ([ID_PARTICIPANTE], [ID_ACTIVIDAD], [NOMBRE_PARTICIPANTE], [ID_USUARIO]) VALUES (18, 5, N'Ana', 2)
INSERT [dbo].[PARTICIPANTES] ([ID_PARTICIPANTE], [ID_ACTIVIDAD], [NOMBRE_PARTICIPANTE], [ID_USUARIO]) VALUES (19, 3, N'Ana', 2)
INSERT [dbo].[PARTICIPANTES] ([ID_PARTICIPANTE], [ID_ACTIVIDAD], [NOMBRE_PARTICIPANTE], [ID_USUARIO]) VALUES (20, 6, N'Alejandro', 4)
INSERT [dbo].[PARTICIPANTES] ([ID_PARTICIPANTE], [ID_ACTIVIDAD], [NOMBRE_PARTICIPANTE], [ID_USUARIO]) VALUES (21, 6, N'Luis', NULL)
INSERT [dbo].[PARTICIPANTES] ([ID_PARTICIPANTE], [ID_ACTIVIDAD], [NOMBRE_PARTICIPANTE], [ID_USUARIO]) VALUES (22, 6, N'Jaime', NULL)
INSERT [dbo].[PARTICIPANTES] ([ID_PARTICIPANTE], [ID_ACTIVIDAD], [NOMBRE_PARTICIPANTE], [ID_USUARIO]) VALUES (23, 6, N'Marcos', NULL)
GO
INSERT [dbo].[REPARTOS_GASTO] ([IDREPARTO], [IDGASTO], [IDPARTICIPANTE], [CANTIDAD]) VALUES (17, 9, 15, 1148)
INSERT [dbo].[REPARTOS_GASTO] ([IDREPARTO], [IDGASTO], [IDPARTICIPANTE], [CANTIDAD]) VALUES (18, 10, 15, 11.25)
INSERT [dbo].[REPARTOS_GASTO] ([IDREPARTO], [IDGASTO], [IDPARTICIPANTE], [CANTIDAD]) VALUES (19, 10, 16, 11.25)
INSERT [dbo].[REPARTOS_GASTO] ([IDREPARTO], [IDGASTO], [IDPARTICIPANTE], [CANTIDAD]) VALUES (20, 10, 17, 11.25)
INSERT [dbo].[REPARTOS_GASTO] ([IDREPARTO], [IDGASTO], [IDPARTICIPANTE], [CANTIDAD]) VALUES (21, 10, 18, 11.25)
INSERT [dbo].[REPARTOS_GASTO] ([IDREPARTO], [IDGASTO], [IDPARTICIPANTE], [CANTIDAD]) VALUES (22, 11, 20, 30)
INSERT [dbo].[REPARTOS_GASTO] ([IDREPARTO], [IDGASTO], [IDPARTICIPANTE], [CANTIDAD]) VALUES (23, 11, 21, 30)
INSERT [dbo].[REPARTOS_GASTO] ([IDREPARTO], [IDGASTO], [IDPARTICIPANTE], [CANTIDAD]) VALUES (24, 11, 22, 30)
INSERT [dbo].[REPARTOS_GASTO] ([IDREPARTO], [IDGASTO], [IDPARTICIPANTE], [CANTIDAD]) VALUES (25, 11, 23, 30)
INSERT [dbo].[REPARTOS_GASTO] ([IDREPARTO], [IDGASTO], [IDPARTICIPANTE], [CANTIDAD]) VALUES (26, 12, 20, 3.75)
INSERT [dbo].[REPARTOS_GASTO] ([IDREPARTO], [IDGASTO], [IDPARTICIPANTE], [CANTIDAD]) VALUES (27, 12, 21, 3.75)
INSERT [dbo].[REPARTOS_GASTO] ([IDREPARTO], [IDGASTO], [IDPARTICIPANTE], [CANTIDAD]) VALUES (28, 12, 22, 3.75)
INSERT [dbo].[REPARTOS_GASTO] ([IDREPARTO], [IDGASTO], [IDPARTICIPANTE], [CANTIDAD]) VALUES (29, 12, 23, 3.75)
GO
INSERT [dbo].[SEGURIDAD_USUARIOS] ([ID_USUARIO], [SALT], [PASSWORD_HASH], [TOKEN_RECUPERACION], [TOKEN_EXPIRACION]) VALUES (3, N'É¦YÛOìîÏÑ4"Åx¬ÔÌNËö[áO_®µØf ·4æ©ïÓõ6µl?', 0x027EB342309B484136F163ADF810D084573DE4FF72ABDB2BEFC211B15A3ECFF35901E6A5192055ABBA15AA29A6ED917E176295A684FF7BCB556CC89900C0D63C, NULL, NULL)
INSERT [dbo].[SEGURIDAD_USUARIOS] ([ID_USUARIO], [SALT], [PASSWORD_HASH], [TOKEN_RECUPERACION], [TOKEN_EXPIRACION]) VALUES (4, N'ºHð?DV$ÌwÅ:Hð|Ø(ni^J&èâs?uæGûaÏöà#¥v	Õ0', 0x2F92D2202D58A2774C6D95004238803E73C26CACA386F1B9E7F89AB195A887D2927ECDB45C3568B025627BDCF643A8ABE815DF33E802398CF71B2F9A40B7684C, NULL, NULL)
GO
INSERT [dbo].[USUARIOS] ([ID_USUARIO], [NOMBRE], [EMAIL], [PASSWORD], [ROL]) VALUES (1, N'Carlos', N'carlos@test.com', N'1234', N'USER')
INSERT [dbo].[USUARIOS] ([ID_USUARIO], [NOMBRE], [EMAIL], [PASSWORD], [ROL]) VALUES (2, N'Ana', N'ana@test.com', N'1234', N'USER')
INSERT [dbo].[USUARIOS] ([ID_USUARIO], [NOMBRE], [EMAIL], [PASSWORD], [ROL]) VALUES (3, N'alex', N'alex@test.com', N'1234', N'USER')
INSERT [dbo].[USUARIOS] ([ID_USUARIO], [NOMBRE], [EMAIL], [PASSWORD], [ROL]) VALUES (4, N'Alejandro', N'alexruiz.g23@gmail.com', N'12345', N'USER')
GO
ALTER TABLE [dbo].[ACTIVIDADES]  WITH CHECK ADD  CONSTRAINT [FK_Actividades_Usuarios] FOREIGN KEY([ID_CREADOR])
REFERENCES [dbo].[USUARIOS] ([ID_USUARIO])
GO
ALTER TABLE [dbo].[ACTIVIDADES] CHECK CONSTRAINT [FK_Actividades_Usuarios]
GO
ALTER TABLE [dbo].[GASTOS]  WITH CHECK ADD  CONSTRAINT [FK_Gastos_Actividades] FOREIGN KEY([ID_ACTIVIDAD])
REFERENCES [dbo].[ACTIVIDADES] ([ID_ACTIVIDAD])
GO
ALTER TABLE [dbo].[GASTOS] CHECK CONSTRAINT [FK_Gastos_Actividades]
GO
ALTER TABLE [dbo].[GASTOS]  WITH CHECK ADD  CONSTRAINT [FK_Gastos_Participantes] FOREIGN KEY([ID_PAGADOR])
REFERENCES [dbo].[PARTICIPANTES] ([ID_PARTICIPANTE])
GO
ALTER TABLE [dbo].[GASTOS] CHECK CONSTRAINT [FK_Gastos_Participantes]
GO
ALTER TABLE [dbo].[LISTA_COMPRA]  WITH CHECK ADD  CONSTRAINT [FK_ListaCompra_Actividades] FOREIGN KEY([ID_ACTIVIDAD])
REFERENCES [dbo].[ACTIVIDADES] ([ID_ACTIVIDAD])
GO
ALTER TABLE [dbo].[LISTA_COMPRA] CHECK CONSTRAINT [FK_ListaCompra_Actividades]
GO
ALTER TABLE [dbo].[LISTA_COMPRA]  WITH CHECK ADD  CONSTRAINT [FK_ListaCompra_Gastos] FOREIGN KEY([ID_GASTO])
REFERENCES [dbo].[GASTOS] ([ID_GASTO])
GO
ALTER TABLE [dbo].[LISTA_COMPRA] CHECK CONSTRAINT [FK_ListaCompra_Gastos]
GO
ALTER TABLE [dbo].[PARTICIPANTES]  WITH CHECK ADD  CONSTRAINT [FK_Participantes_Actividades] FOREIGN KEY([ID_ACTIVIDAD])
REFERENCES [dbo].[ACTIVIDADES] ([ID_ACTIVIDAD])
GO
ALTER TABLE [dbo].[PARTICIPANTES] CHECK CONSTRAINT [FK_Participantes_Actividades]
GO
ALTER TABLE [dbo].[PARTICIPANTES]  WITH CHECK ADD  CONSTRAINT [FK_Participantes_Usuarios] FOREIGN KEY([ID_USUARIO])
REFERENCES [dbo].[USUARIOS] ([ID_USUARIO])
GO
ALTER TABLE [dbo].[PARTICIPANTES] CHECK CONSTRAINT [FK_Participantes_Usuarios]
GO
ALTER TABLE [dbo].[REPARTOS_GASTO]  WITH CHECK ADD  CONSTRAINT [FK_Repartos_Gastos] FOREIGN KEY([IDGASTO])
REFERENCES [dbo].[GASTOS] ([ID_GASTO])
GO
ALTER TABLE [dbo].[REPARTOS_GASTO] CHECK CONSTRAINT [FK_Repartos_Gastos]
GO
ALTER TABLE [dbo].[REPARTOS_GASTO]  WITH CHECK ADD  CONSTRAINT [FK_Repartos_Participantes] FOREIGN KEY([IDPARTICIPANTE])
REFERENCES [dbo].[PARTICIPANTES] ([ID_PARTICIPANTE])
GO
ALTER TABLE [dbo].[REPARTOS_GASTO] CHECK CONSTRAINT [FK_Repartos_Participantes]
GO
ALTER TABLE [dbo].[SEGURIDAD_USUARIOS]  WITH CHECK ADD  CONSTRAINT [FK_Seguridad_Usuarios] FOREIGN KEY([ID_USUARIO])
REFERENCES [dbo].[USUARIOS] ([ID_USUARIO])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[SEGURIDAD_USUARIOS] CHECK CONSTRAINT [FK_Seguridad_Usuarios]
GO
USE [master]
GO
ALTER DATABASE [RANDOMPAY] SET  READ_WRITE 
GO
